name: Netra Scan on PR

on:
  pull_request:
    # Trigger on PR events like opened, synchronize, and reopened
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Debug GitHub Context
        run: |
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_EVENT_BEFORE: ${{ github.event.before }}"

      - name: Run netra scan on each file
        run: |
          #!/bin/bash

          # Fetch the list of files changed in the commit
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          echo "-----changed_files-------"
          echo $changed_files
          echo "-----------------"
          # Loop through each file and run the netra scan command
          for file in $changed_files; do
            if [[ -f "$file" ]]; then
              echo "Scanning file: $file"
              ./netra scan --llm --llm-provider ollama --llm-model llama3:8b --llm-api-key "s" "$file"
            fi
          done
          echo "-----done-------"
